# Fail the build when the generated XRobot entry no longer matches its inputs.
#
# Run in script mode:
#   cmake -DXROBOT_MAIN_HEADER=<header> -DXROBOT_BSP_ROOT=<dir> -P XRobotFreshness.cmake
#
# The header names its inputs in "// xrobot: config|entry|depends" lines, with paths
# relative to the header directory unless absolute, and records their digest in a
# "// xrobot: digest" line. Each input, in line order, contributes the line
# "<path> <SHA-256 of its content>\n", and the digest is the SHA-256 of these lines. The
# content of the entry source is only its XR_REGISTER calls, each up to the next semicolon
# and followed by a newline, taken after every carriage return is removed; any other input
# counts as the bytes of the whole file. xrobot computes the digest the same way
# (xrobot.project.input_digest). File times play no part, and the header is never
# regenerated here.

if(NOT EXISTS "${XROBOT_MAIN_HEADER}")
  message(
    FATAL_ERROR "[XRobot] ${XROBOT_MAIN_HEADER} is missing. Run `xrobot setup` in "
                "${XROBOT_BSP_ROOT}."
  )
endif()

get_filename_component(_dir "${XROBOT_MAIN_HEADER}" DIRECTORY)
file(STRINGS "${XROBOT_MAIN_HEADER}" _lines REGEX "^// xrobot: " ENCODING UTF-8)
set(_config "<config>")
set(_listing "")
set(_recorded "")
foreach(_line IN LISTS _lines)
  if(_line MATCHES "^// xrobot: digest ([0-9a-f]+)$")
    set(_recorded "${CMAKE_MATCH_1}")
    continue()
  endif()
  # The configure step has rejected any other kind of "// xrobot:" line.
  if(NOT _line MATCHES "^// xrobot: (config|entry|depends) \"([^\"]+)\"$")
    continue()
  endif()
  set(_kind "${CMAKE_MATCH_1}")
  set(_path "${CMAKE_MATCH_2}")
  set(_file "${_path}")
  if(NOT IS_ABSOLUTE "${_file}")
    set(_file "${_dir}/${_file}")
  endif()
  get_filename_component(_file "${_file}" ABSOLUTE)
  if(_kind STREQUAL "config")
    file(RELATIVE_PATH _config "${XROBOT_BSP_ROOT}" "${_file}")
  endif()
  if(NOT EXISTS "${_file}")
    message(
      FATAL_ERROR
        "[XRobot] ${XROBOT_MAIN_HEADER} was generated from ${_file}, which no longer "
        "exists. Run `xrobot gen -c ${_config}` in ${XROBOT_BSP_ROOT}."
    )
  endif()
  if(_kind STREQUAL "entry")
    # file(READ) turns CRLF into LF on Windows and keeps it elsewhere; without carriage
    # returns both read the same text. file(SHA256) below hashes the bytes on every host.
    file(READ "${_file}" _rest)
    string(REPLACE "\r" "" _rest "${_rest}")
    set(_content "")
    while(_rest MATCHES "XR_REGISTER[^;]*")
      set(_match "${CMAKE_MATCH_0}")
      string(APPEND _content "${_match}\n")
      string(FIND "${_rest}" "${_match}" _at)
      string(LENGTH "${_match}" _length)
      math(EXPR _at "${_at} + ${_length}")
      string(SUBSTRING "${_rest}" ${_at} -1 _rest)
    endwhile()
    string(SHA256 _hash "${_content}")
  else()
    file(SHA256 "${_file}" _hash)
  endif()
  string(APPEND _listing "${_path} ${_hash}\n")
endforeach()

if(_recorded STREQUAL "")
  message(
    FATAL_ERROR
      "[XRobot] ${XROBOT_MAIN_HEADER} records no digest of its inputs; it was generated by "
      "an older xrobot. Run `xrobot gen -c ${_config}` in ${XROBOT_BSP_ROOT}."
  )
endif()
string(SHA256 _actual "${_listing}")
if(NOT _actual STREQUAL _recorded)
  message(
    FATAL_ERROR
      "[XRobot] ${XROBOT_MAIN_HEADER} is stale: its inputs changed after it was generated. "
      "Run `xrobot gen -c ${_config}` in ${XROBOT_BSP_ROOT} before building."
  )
endif()
